[package]
name = "carrypigeon-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.0"
sqlx = { version = "0.7.4", features = ["runtime-tokio","postgres","json","chrono"]}
tracing = "0.1.40"
tracing-appender = "0.2.3"
tracing-error = "0.2.0"
tracing-subscriber = {version = "0.3.18", features = ["env-filter"]}
tokio = "1.37.0"
tokio-test = "0.4.4"
serde = {version = "1.0.200" ,features = ["derive"]}
serde_json = "1.0.116"
chrono = "0.4.38"
rocket_ws = "0.1.0"
redis = { version = "0.25.3", features = ["tokio-rustls-comp"] }
jsonwebtoken= {version = "9.3.0", features = ["use_pem"]}
rsa = "0.9.6"
rand = "0.8.5"
pkcs8 = {version = "0.10.2", features = ["alloc"]}
