[package]
name = "carrypigeon-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.1"
sqlx = { version = "0.7.4", features = ["runtime-tokio","postgres","json","chrono"]}
tracing = "0.1.40"
tracing-appender = "0.2.3"
tracing-error = "0.2.0"
tracing-subscriber = {version = "0.3.18", features = ["env-filter"]}
tokio = "1.38.0"
tokio-test = "0.4.4"
serde = {version = "1.0.203" ,features = ["derive"]}
serde_json = "1.0.117"
chrono = "0.4.38"
rocket_ws = "0.1.1"
redis = { version = "0.25.4", features = ["tokio-comp","aio"] }
jsonwebtoken= {version = "9.3.0", features = ["use_pem"]}
rsa = "0.9.6"
rand = {version = "0.8.5", features = ["std_rng"]}
pkcs8 = {version = "0.10.2", features = ["alloc"]}
aes-gcm = "0.10.3"
cbc = {version = "0.1.2", features = ["block-padding","alloc"]}
