[package]
name = "carrypigeon-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.19.0"
async_static = "0.1"
rocket = "0.5.0"
sqlx = { version = "0.7.4", features = ["runtime-tokio","postgres","uuid"]}
tracing = "0.1.40"
tracing-appender = "0.2.3"
tracing-error = "0.2.0"
tracing-subscriber = {version = "0.3.18", features = ["env-filter"]}
tokio = "1.37.0"
tokio-test = "0.4.4"
