[default]
address = "0.0.0.0"
port = 2024
workers = 16
max_blocking = 512
ident = "CarryPigeon"

log_level = "normal"

temp_dir = "/tmp"

cli_colors = true

[default.limits]
json = "5 MiB"
file = "10 MiB"

[default.tls]
certs = "./tls/certs.pem" # Path or bytes to DER-encoded X.509 TLS cert chain.
key = "./tls/key.pem"     # Path or bytes to DER-encoded ASN.1 PKCS#1/#8 or SEC1 key.

[release]
address = "0.0.0.0"

[debug]
address = "127.0.0.1"
