[default]
# release 0.0.0.0
address = "127.0.0.1"
port = 443
workers = 16
max_blocking = 512
ident = "CarryPigeon"

log_level = "normal"

temp_dir = "/tmp"

cli_colors = true

[default.limits]
json = "1 MiB"
file = "5 MiB"